micronaut:
  application:
    name: jenny-admin-api
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    minPoolSize: 1
    maxPoolSize: 10
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true
      sensitive: true
  locations: classpath:db/migration
